# Generated by Django 2.2.6 on 2019-11-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='num_quarto',
            field=models.IntegerField(verbose_name='Número do Quarto'),
        ),
    ]
