# Generated by Django 2.2.7 on 2019-12-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191119_1439'),
        ('core', '0002_auto_20191118_2157'),
    ]

    operations = [
    ]
